project:
  type: website
  render:
    - "*.qmd"
    - "!_scratch/"
  resources:
    - plots/**
    - pictures/**
  output-dir: docs

website:
  title: "Third Place Index"
  navbar:
    background: light
    search: false
    left:
      - href: index.qmd
        text: Dashboard
      - href: methodology.qmd
        text: Methodology
      - href: about.qmd
        text: About

format:
  html:
    theme:
      - cosmo
      - custom.scss
    toc: true
    toc-depth: 2
    smooth-scroll: true
    page-layout: full