project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!scripts/"
  resources:
    - plots/**
    
website:
  title: "Map dashboard"
  navbar:
    left:
      - href: index.qmd
        text: Dashboard
      - href: about.qmd
        text: About
      - href: methodology.qmd
        text: Methodology

format:
  html:
    theme: flatly
    page-layout: full
    toc: false
