---
title: "About"
---

# Third Places

The term *third place* was coined by sociologist Ray Oldenburg in his 1989 book \_The Great Good Places\_. Third Places are spaces open to the public in which they can informally gather, mingle, and pass time, such as restaurants, cafés, bookstores, or libraries. The term "Third Place" stems from the distinction from "First Places" (the home) and "Second Places" (work and education). See Methodology for a full list of Third Places included in our definition.

The Third Place Index, following a publication from the US by \[<https://thirdplaceindex.org/#about>\](Evan O'Neil), maps the availability of Third Places in the Netherlands. It gives a score to each area ranging from 0 to 100 describing how good the availability of Third Places is compared to other areas in the Netherlands. Low numbers indicate places with few Third Places and with higher danger of isolation while higher numbers indicate a wider availability of community building.

\[methodology.html\](View the full description of the methodology)
