---
title: "Methodology"
---

# Overview

The KROEG index is an index based on the Third Place Index (TPI) (https://thirdplaceindex.org) the number of businesses, companies and instances within a postcode area. **KROEG** stands for *Kaart van Ruimtelijke Ontmoetingsplekken en Externe Gemeenschap* in Dutch and *KVK-based Ranking of Opportunities for Engagement and Gathering* in English. 

The KROEG index compares the amount and access to social and health infrastrucutres between postcode areas in the Netherlands. The derived dataset, dashboard and index can be utilized for inference and comparison between postcode area's for research and policymakers to analyse access to certain infrasctructures. 

# Data

We drew upon data from the [Dutch Chamber of Commerce](https://www.kvk.nl/) to build the Third Place Index. We classified all registered entities in the Dutch Chamber of Commerce as belonging to one of the following sectors: 

- Food & Beverage: e.g, restaurants, cafés, or bars
- Retail: e.g., supermarkets, department stores, or small business
- Community Centres: e.g., libraries, youth centres
- Cultural Venues: e.g, cinemas, bookstores, or theatres
- Sport & Leisure: e.g., gyms, or attraction parks
- Medical Services: e.g., pharmacies, hospitals, or doctors

The exact codebook can be downloaded on Github:  [Download Sector Classification Codebook](data/sbi_sector_classification_codebook.csv). 

The full KROEG index can be downloaded on Github:  

- [Download KROEG Index as CSV File](data/KROEG_index.csv)
- [Download KROEG Index as GPKG File](data/KROEG_index.gpkg)


# The Index

We calculated the number of Third Places of each of these sectors per PC-4 postcode. Then, we ranked the PC-4 postcode regions based on their number of Third Places in a given sector and calculated percentiles. This resulted in a score from 0 to 100. A value of 85 in the medical sector, for instance, means that this postcode has more medical services than 85% of the other postcodes. The data only contain this index and not the sum of Third Places per postcode as we could not export these numbers for postcodes with fewer than 10 companies due to the policy regulations of the CBS and of ODISSEI.

We also aggregated the sectors and calculated: 

- The total availability of Third Places
- The total availability of Third Places excluding medical services
- The total availability of Third Places excluding medical services and retail

# Level of Urbanisation

Additionally, as the index --- almost by definition --- maps urban vs non-urban areas, we calculated each of these indices within the different levels of urbanisation. This means that the number of Third Places in a postcode is only compared to the number of Third Places in postcodes with the same degree of urbanisation. The urbanisation categories used by Statistics Netherlands (see [see the CBS urbanisation categories](https://www.cbs.nl/en-gb/our-services/methods/definitions/degree-of-urbanisation)) are: 

- Extremely urbanised: more than 2,500 addresses / km^2
- Strongly urbanised: between 1,500 and 2,500 addresses / km^2
- Moderately urbanised: between 1,000 and 1,500 addresses / km^2
- Hardly urbanised: between 500 and 1,000 addresses / km^2
- Not urbanised: less than 500 addresses / km^2


